### ISSUE TITLE
Evaluate the Tekton pull request reporting

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/lighthouse#1]
Evaluate the Tekton pull request reporting: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource

**Comment by ccojocar** [comment]
Design document for [Tekton triggering](https://docs.google.com/document/d/1fngeNn3kGD4P_FTZjAnfERcEajS7zQhSEUaN7BYIlTw/edit?ts=5d0432e5#heading=h.x3gegx3gu7lb)

Reporting command which is built into the Tekton pipeline for GitHub:
https://github.com/tektoncd/pipeline/pull/895
https://github.com/tektoncd/pipeline/issues/778

**Comment by jstrachan** [comment]
for now we're going with our own webhook handler to trigger meta pipeline + handle ChatOps

we can revisit in the future. We're hoping to use Tekton for reporting pipeline status to git

**Comment by ccojocar** [comment]
@wbrefvem I am going to take over and evaluate the Tekton Pull Request resource (https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource).
