### ISSUE TITLE
[Question] What is the advantage of lighthouse compared with prow

### ISSUE THREAD

**Issue by gyliu513** [jenkins-x/lighthouse#1006]
Can anyone show some comments for this question? Seems prow is more popular and I can see all of the kubernetes ecosystem projects are using prowl And I was evaluating which one to use for internal CICD process management, and hope get some comments from you. Thanks!

**Comment by eddycharly** [comment]
Advantages for lighthouse: it works with other scm providers than github (gitlab, bitbucket), it supports the jenkins-x engine and has better support for tekton.

Advantages for prow: it has a frontend, it supports the k8s engine, has features that lighthouse does not have yet (related to logs for example).

**Comment by gyliu513** [comment]
Thanks @eddycharly , this really helpful!

More question here, I can see the lighthouse can work with prow plugins and prow configs, so does this mean that the lighthouse can also leverage prow to check logs?

> related to logs for example

What do you mean logs? I can see prow do have logs for build, test, etc, do you mean this log?

**Comment by eddycharly** [comment]
Yes, logs that come out from your running jobs. 

To be exact it’s not only a matter of lighthouse vs prow, it also depends on the engine used.

Prow with the k8s engine takes care of logs. 
Lighthouse with the jenkins-x engine will probably take care of logs too. 
Neither prow or lighthouse with the tekton engine will take care of logs. 

For tekton, there is a solution at the tekton level though. That should apply to both prow and lighthouse.

**Comment by eddycharly** [comment]
Regarding tekton pipelines, prow uses v1alpha1 and lighthouse uses v1beta1.

Now I guess it all depends on your needs. Do you need a solution that works with gitlab ou github only is fine ? What are the engines you want to leverage ? Etc...

**Comment by eddycharly** [comment]
And I find prow more difficult to deploy, more components, no helm charts...

**Comment by gyliu513** [comment]
Thanks for your detailed explanation, @eddycharly !

So here what I need is just for Github enterprise, and want to leverage k8s engine. Seems both PROW and Lighthouse works for this situation. Let me check more for those two solutions.

**Comment by eddycharly** [comment]
Both support github enterprise but lighthouse does not support the k8s engine yet.
