### ISSUE TITLE
Creating issues for hacktoberfest

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#1009]
How about creating some issues to help with hacktoberfest contributions ?

Some ideas that could be easy to pickup for newcomers:
- add dog plugin
- add goose plugin
- add pony plugin
- add a semantic pr plugin

**Comment by abayer** [comment]
Sounds good to me! Though we already have the dog and pony plugins. =)

**Comment by eddycharly** [comment]
Arrrf, missed that. Anyway contributing in the plugins area could be a good starting point for newcomers as it doesn’t require a deep knowledge of lighthouse code base.

**Comment by eddycharly** [comment]
Maybe we can add `golint` to the list ?

**Comment by eddycharly** [comment]
Closing, issues are getting created.
