### ISSUE TITLE
Proposal: replace lighthouse and plugins config by CRDs

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#1013]
Working with config maps has several drawbacks like the need to watch for changes, mounting the config maps in pod can be problematic when config maps don't exist and pods getting stuck as kubelet cannot start the pods etc...

It also makes the configuration more complex as there is no notion of repository in the config, every config section that needs to know about repositories gets a list of org/repo that apply for the section.

Managing multiple config is not possible and it can be problematic if different repos want to configure plugins in a different way (shall the size plugin thresholds be the same for every team for example).

To solve this, i propose two new CRDs `RepoConfig` and `PluginConfig`. Those two CRDs would replace the current file based configuration.

The `RepoConfig` would hold the config to be applied to one repository and the `PluginConfig` would hold the config related to the plugins. Additionally, one `RepoConfig` would reference a `PluginConfig` that applies for this repository.

It would allow for simpler configuration and enable multiple config to leave together. No need to watch config maps anymore, the CRDs live in etcd and are somewhat ambient in the cluster.

Considering the webhooks component for example, it could receive web hooks from various scm providers and be able to process them correctly.

This would be a huge change though and needs special attention to not break jx compatibility but it should be doable and could provide some nice benefits.

I have a working prototype i implemented here [eddycharly/kloops](https://github.com/eddycharly/kloops), it covers only the webhook part for now and i ported a few plugins but not all yet.

It is part of a project i'm making for myself and is strongly inspired from Prow/Lighthouse.

Just wanted to discuss it if you think it can benefit to Lighthouse, i'd be happy to see if things can converge.

**Comment by abayer** [comment]
That seems reasonable to me. We need to be able to keep supporting the config maps since that's what Jenkins X and any other existing users will be doing, but we could have something watching for changes to the configmaps that then populates/updates the CRDs accordingly?

**Comment by eddycharly** [comment]
> we could have something watching for changes to the configmaps that then populates/updates the CRDs accordingly?

Yeah, that was my idea. I guess it's updated through the config updater plugin ?

**Comment by eddycharly** [comment]
Ah ok, i hoped it was based on config updater and that we could have dropped the config maps entirely. But watching the config maps can work too.
