### ISSUE TITLE
Question : best way to fake an scm provider client

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#1037]
Quick question. What should be the best way to fake an scm provider client ?

I see there is one fake driver in go-scm but some methods are not implemented.
Another fake package lives in the scmprovider package but I can’t create a plugin agent with it.

If we had to pick one of both solutions which one should we use ?

/cc @abayer

**Comment by abayer** [comment]
So I think the one in `scmprovider` dates back to Prow, while the one in `go-scm` comes from `go-scm`. Obviously. =) I think the right way to go would be to get the `go-scm` fake driver fully implemented for what we'd need.

**Comment by eddycharly** [comment]
Ok, shall I contribute there then ?

What I’m trying to do is to adapt the plugins tests to invoke them through the plugin engine (as there is some logic that is managed at the engine level.

**Comment by eddycharly** [comment]
What I don’t like with this approach is that one plugin is harder to test but it’s a plugin so I guess it makes sense to use a sort of host when testing...

**Comment by eddycharly** [comment]
Or I can remove the tests where some engine logic is involved (mostly filtering and matching a refer)

**Comment by abayer** [comment]
Yeah, feel free to contribute to go-scm - ping me on any PRs and I'll review them.

**Comment by eddycharly** [comment]
Arrf, `Milestone` CRUD is not implemented at all :(

**Comment by eddycharly** [comment]
Closing, I agree that faking the driver would be a better option.
/close
