### ISSUE TITLE
Webhook response 403 Forbidden: Invalid X-Hub-Signature

### ISSUE THREAD

**Issue by zxDiscovery** [jenkins-x/lighthouse#1040]
I follow the [doc](https://github.com/jenkins-x/lighthouse/blob/master/docs/INSTALL.md#installation) to create a webhook for my github repo. But the webhook get the response 403
```
Headers
Content-Length: 39
Content-Type: text/plain; charset=utf-8
Date: Wed, 09 Sep 2020 11:25:59 GMT
Via: 1.1 google
X-Content-Type-Options: nosniff
Body
403 Forbidden: Invalid X-Hub-Signature
```

**Comment by zxDiscovery** [comment]
![截屏2020-09-11上午11 09 29](https://user-images.githubusercontent.com/40016978/92850640-452d9480-f41f-11ea-9bb0-62ca1deb2558.png)

**Comment by hferentschik** [comment]
The error seems to indicate that the webhook secret you configured in the webhook is not matching the secret you configured in Lighthouse. 

If you go to the GitHub UI and edit the settings for the webhook you can see the webhook secret configured on GitHub.
You need to compare this to the secret in `lighthouse-hmac-token`.

```
kubectl get secret lighthouse-hmac-token -o  jsonpath="{['data']['hmac']}" | base64 -D
```

They need to match. If they don't match something must have gone wrong or there is an error in the scripts/steps.

**Comment by hferentschik** [comment]
Looking at the scripts, the `helm install` step is where the secret will be created in the cluster:

```
webhook_secret=<generated-webhook-secret>

helm install -n $install_namepsace lighthouse lighthouse/lighthouse \
  --set git.kind=github \
  --set git.name=github \
  --set git.server=https://github.com \
  --set hmacToken=$webhook_secret \
  --set user=$bot_user \
  --set oauthToken=$GITHUB_TOKEN \
  --set engines.tekton=true \
  --set tektoncontroller.dashboardURL=$tekton_dash_url \
  --set createIngress=true \
  --set domainName=$domain
```

And this is the `gh` command which generates the webhook:

```
webhook_secret=<generated-webhook-secret>

cat <<EOF | gh api -X POST repos/$bot_user/$repo_name/hooks --input -
{
  "name": "web",
  "active": true,
  "events": [
    "*"
  ],
  "config": {
    "url": "$webhook_url",
    "content_type": "json",
    "insecure_ssl": "0",
    "secret": "$webhook_secret"
  }
}
EOF
```

Assuming you did not change `webhook_secret` between running the commands it should work. Did you by any chance generate two different secrets?

**Comment by zxDiscovery** [comment]
The `webhook_secret` I generated by this command `ruby -rsecurerandom -e 'puts SecureRandom.hex(42)'.  And the webhook_secret in github is the same in the lighthouse-hmac-token.

```
root@suasion1:~# kubectl get secret -n lighthouse lighthouse-hmac-token -o  jsonpath="{['data']['hmac']}"
ZGI0MGE5NTllMmZmNWM2MWJiNTEzMWNiZGI5OGQwNGRhOWQ5MDllYjc3NWIxZDMwYzRmNTIxZGVkYmQyMzIyN2MwOTFiMDE0MGE4YmFhZWYyYjg2
root@suasion1:~# echo "ZGI0MGE5NTllMmZmNWM2MWJiNTEzMWNiZGI5OGQwNGRhOWQ5MDllYjc3NWIxZDMwYzRmNTIxZGVkYmQyMzIyN2MwOTFiMDE0MGE4YmFhZWYyYjg2"| base64 -d
db40a959e2ff5c61bb5131cbdb98d04da9d909eb775b1d30c4f521dedbd23227c091b0140a8baaef2b86
```

**Comment by zxDiscovery** [comment]
![截屏2020-09-11下午3 47 50](https://user-images.githubusercontent.com/40016978/92886346-27bff100-f446-11ea-9a84-bb14c5f73ae6.png)

**Comment by eddycharly** [comment]
It looks like you installed prow too, are you sure it is lighthouse receiving the webhook ?

BTW you know you're not supposed to share your secrets right ? =)

**Comment by zxDiscovery** [comment]
@eddycharly  Yes, I also installed the prow. If it conflict I will uninstall prow. The secrets I will re-generate. Thanks, ^_^

**Comment by eddycharly** [comment]
Not sure but prow also has a webhooks handler that uses the same path as lighthouse so it's worth checking who is receiving the webhook from github.

**Comment by hferentschik** [comment]
As @eddycharly, worth checking the ingresses and the logs. Make sure the webhook URL is pointing to the right service and there should be something in the Lighthouse logs of the webhook deployment.

**Comment by zxDiscovery** [comment]
The webhooks conflict with the Prow's webhooks. After I uninstall prow, the webhook can work normally. 
@hferentschik @eddycharly Thank you!
