### ISSUE TITLE
Possible to use prow external-plugins with lighthouse?

### ISSUE THREAD

**Issue by hassenius** [jenkins-x/lighthouse#1074]
Hi,

I'm curious whether it's possible to use the [external-plugins](https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins) from prow  with lighthouse. It appears that these are structured a little bit differently from the other plugins, so not sure if that has any implications on porting to lighthouse. I'm particularly interested in the cherry-picker (although it seems it can also run standalone as a workaround)

**Comment by eddycharly** [comment]
Hi @hassenius !
I don't think Prow external plugins are usable as-is, mainly because Lighthouse sends the webhook in go-scm format, not the raw webhook event.

**Comment by LinuxSuRen** [comment]
hi @eddycharly, I didn't find any doc about how to use an external plugin of lighthouse.

**Comment by eddycharly** [comment]
Hi, dunno if there are external plugins available. If I remember correctly it was supported in lighthouse but one has to write plugins though.
