### ISSUE TITLE
Renamed repo breaks lighthouse normal function

### ISSUE THREAD

**Issue by apenen** [jenkins-x/lighthouse#1116]
Hi!

When someone renames a project in git (badly done)... The current PR job has to be deleted or jx cannot continue with the next.

{"component":"keeper","error":"failed to perform REST query for PRs: listing all open pull requests for <old name project>: 404 Project Not Found","file":"/workspace/source/cmd/keeper/main.go:182","func":"main.sync","level":"error","msg":"Error syncing.","time":"2020-10-16T06:48:28Z"}

Any ideas?

**Comment by keskad** [comment]
Hi, I have exactly the same issue. I think its pretty critical in my opinion, here is the use case:

- Non-administrative user deletes his own repository from Gitlab/Github
- Then `lighthouse-keeper` does not work for ANY project on Jenkins X and nobody knows why
