### ISSUE TITLE
Approved review in Github by an OWNER doesn't make the PR "/approve"d

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/lighthouse#1123]
Not sure if it's a problem from my installation or if it's the same for everybody, but when I'm approving a review of a PR (not mine) in Github on a project I'm one of the OWNERS, lighthouse doesn't seems to consider this as an approval like "/approve", I have to add an "/approve" comment to get it in the merge pool.

Is it normal? If not, how can I debug this?  

```
- chart: jenkins-x/lighthouse
  version: 0.0.851
```

![](https://user-images.githubusercontent.com/52448671/96989000-622cab80-1525-11eb-8c39-9ca301b2b486.png)

**Comment by jstrachan** [comment]
there's details of how you can run lighthouse locally + debug it via delve or your IDE: https://github.com/jenkins-x/lighthouse#testing

**Comment by hervelemeur** [comment]
I've pushed another commit to the PR in order to retest the approval of a review, but then my bot immediatly added the "approved" label.

[On Slack](https://kubernetes.slack.com/archives/C9MBGQJRH/p1603449565227600?thread_ts=1603442866.214900&cid=C9MBGQJRH) I've been told that

> For that to work you need to have the `review_acts_as_approve` option set in your scheduler config.However, the webhook that `jx-gitops` creates is missing the review event,  because it's in turn missing from go-scm:  
> jenkins-x/go-scm#196

**Comment by hervelemeur** [comment]
Seems to be resolved by jenkins-x/go-scm#202, I'll have to test again :)

**Comment by hervelemeur** [comment]
Resolved by [https://github.com/jenkins-x/go-scm/pull/202](https://github.com/jenkins-x/go-scm/pull/202) and updating webhook events in github repo settings
