### ISSUE TITLE
"/override" should cancel the overriden build

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/lighthouse#1124]
When a build is in progress, the command "/override pr" (for example) doesn't cancel the "pr" build.

Lighthouse marks the pr build as overriden, but as soon as the build finish, if it failed, it override itself the "/override" command, and force the user to "/override" again the build.

Doesn't lighthouse should cancel any overriden build to avoid this problem?

**Comment by hervelemeur** [comment]
`/remove-lifecycle stale`

**Comment by msvticket** [comment]
I think the suggested behaviour would be surprising for the user. If the user would like to cancel the build that can be done separately with `jx pipeline stop`
