### ISSUE TITLE
Inrepo trigger config file naming different when in a subfolder

### ISSUE THREAD

**Issue by clement-buchart** [jenkins-x/lighthouse#1126]
Hello, 

While looking for the triggers inrepo config, we look for `.lighthouse/trigger.yaml` or any `.lighthouse/*/triggerS.yaml` file
https://github.com/jenkins-x/lighthouse/blob/08b0ae6ebc6a1feb4efafb2d77cae1149f151393/pkg/triggerconfig/inrepo/load_triggers.go#L42-L62

Is it on purpose that the plurality changes where looking at the root of the `.lighthouse` folder ? 
If not, would you like me to submit a PR adding `.lighthouse/triggers.yaml` as an option (maybe keeping `.lighthouse/trigger.yaml` for backward compatibility for now) ?

**Comment by jstrachan** [comment]
@clement-buchart great catch - it should use the same file name in both cases; so lets use `triggers.yaml` for both?
