### ISSUE TITLE
comment `lgtm` in gitlab but always returns "you cannot LGTM your own PR."

### ISSUE THREAD

**Issue by soulseen** [jenkins-x/lighthouse#1154]
when I installed lighthouse witn provider gitlab, and it running well. But I comment `lgtm` in Merge Requests, it always returns 

**you cannot LGTM your own PR.**

<details>

In response to [this]():

>/lgtm

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

----------------------
No matter what user created MR, or what user commented on `LGTM`, the bot always returns it above.

### what's more
I found the cause is Comment author same with MergeReuests author. ref https://github.com/jenkins-x/lighthouse/blob/master/pkg/plugins/lgtm/lgtm.go#L267

and the root cause is in [jenkins-x/go-scm](https://github.com/jenkins-x/go-scm), the func [convertMergeRequestCommentHook](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/gitlab/webhook.go#L288) is used the same user to struct [PullRequest](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/gitlab/webhook.go#L332) and [Comment](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/gitlab/webhook.go#L347)

My team has used the lighthouse in a deep way, what are the roadmap of the lighthouse and the next step improvement? and I can provide some help.

**Comment by slimm609** [comment]
I am seeing this same issue on gitlab.

**Comment by slimm609** [comment]
according to https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#comment-on-merge-request

it looks like using object_attributes.author_id and merge_request.author_id would be the proper way to verify if the comment author and merge request author are the same

**Comment by soulseen** [comment]
> according to https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#comment-on-merge-request
> 
> it looks like using object_attributes.author_id and merge_request.author_id would be the proper way to verify if the comment author and merge request author are the same

agree

**Comment by jstrachan** [comment]
anyone fancy creating the PR on go-scm to use the correct user id field?

**Comment by jeremyrickard** [comment]
Hey @jstrachan i think I have some time this week to take a look (unless @soulseen wants to contribute)

**Comment by jstrachan** [comment]
@jeremyrickard that would be totally awesome! ping us [on slack](https://jenkins-x.io/community/#slack)  if you get stuck with anything

**Comment by slimm609** [comment]
@jeremyrickard and I talked about it today for a bit, it looks like the fix can be fully solved in go-scm gitlab driver and shouldn't need any changes from lighthouse/lgtm (besides being rebuilt to pick up the changes)

**Comment by jstrachan** [comment]
@slimm609 awesome! incidentally whenever go-scm is released there's an automated PR on lighthouse and a new release

**Comment by slimm609** [comment]
We have a "hacky" fix working to make sure it would fix the issue properly.    @soulseen if you want to test in a test environment, you can pull `slimm609/test-jx:webhook5` from dockerhub and make sure it works.   

It will also log the commenter ID and the author ID to the logs of the webhook container. 

Its a little more work to fix it properly but we know how to fix

**Comment by soulseen** [comment]
@slimm609 wonderful! I used it in test env, and it works well.

**Comment by jeremyrickard** [comment]
I've opened a PR in go-scm to address this. Essentially, when the `convertMergeRequestCommentHook` method runs, the previous code was just building up a single user object. Really need to fetch both the comment user and the MR user and set them appropriately, to ensure that things are handled properly. This PR adds logic to fetch the user objects (adds a reference to the gitlab user service to do so).

**Comment by jstrachan** [comment]
I think this is all fixed now? let me know if not and we can reopen
