### ISSUE TITLE
Status Comment before Merging

### ISSUE THREAD

**Issue by RafalMaleska** [jenkins-x/lighthouse#1157]
Prow allows to post results of a CI Job in the MR, this looks like this:

https://github.com/kubernetes/kubernetes/pull/96553#issuecomment-726847400

I'm trying to achive something simmilar with Gitlab. Without success. I believe that Crier 
https://github.com/kubernetes/test-infra/tree/master/prow/crier

and other components are needed to achive this. Is there a plan to do that?

**Comment by jstrachan** [comment]
already in Jenkins X v3 every Pull Request pipeline is linked to the log; so whatever a pipeline does and whether it succeeds or fails you are 1 click away from seeing the logs.

Its easy to add custom comments to a Pull Request via a step / task in the pipeline too. We've a command to comment on a PR: [jx gitops pr comment](https://github.com/jenkins-x/jx-gitops/blob/master/docs/cmd/jx-gitops_pr_comment.md). The [lint pipeline](https://github.com/jenkins-x/jx3-pipeline-catalog/tree/master/tasks/lint) already comments on PRs with any linting failures for any pipelines

The tricky bit is finding what bit of the log to extract and comment; e.g. parsing the output of specific steps in a pipeline to find, say, a java/go/node test failure would be language specific but should not be that hard to do. Particularly as you can easily link to specific lines in the log already in Jenkins X. So someone would need to write a step what parsed the log in a specific step in the pipeline and generated a nice comment
