### ISSUE TITLE
Is that possible to add webhook automatically

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/lighthouse#1227]
We already have the org/repo configuration. If is that possible to add webhook automatically?

**Comment by jstrachan** [comment]
I'd love to support organisation level webhooks. We should be able to easily support this in the `jx gitops webhook update` command. 

it will need some work on https://github.com/jenkins-x/go-scm to handle it for all the different git providers though

**Comment by jstrachan** [comment]
BTW when using Jenkins X you can define all of your orgs/repos in a simple configuration file in `.jx/gitops/source-config.yaml` and the Jenkins X sets up all of the webhooks required along with the associated lighthouse configuration (with optional in-repo configuration or custom scheduler etc)

here's our example from our production setup of how we setup webhooks via a config file: https://github.com/jenkins-x/jx3-eagle/blob/master/.jx/gitops/source-config.yaml

ref docs of the SourceConfig file: https://github.com/jenkins-x-plugins/jx-gitops/blob/main/docs/config.md#gitops.jenkins-x.io/v1alpha1.SourceConfig
