### ISSUE TITLE
Issues with lighthouse annotations (prependStepsURL) for pipelineRuns with multiple tasks

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/lighthouse#1239]
For pipeline runs which have more than one task, the steps are added to only task.

**Comment by jstrachan** [comment]
this is fixed with the new uses: notation - see https://jenkins-x.io/blog/2021/02/25/gitops-pipelines/

**Comment by jstrachan** [comment]
FWIW if you upgrade your pipelines the prependStepsURL annotations are switched to the uses syntax https://jenkins-x.io/v3/develop/pipelines/upgrading/
