### ISSUE TITLE
Project name causes confusion with Google's `Lighthouse`.

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/lighthouse#1386]
Unfortunately, in the 'tech' space, `lighthouse` is pretty commonly associated with Google's [Lighthouse](https://developers.google.com/web/tools/lighthouse) project. Google's project has both been around longer [(3+ years)](https://en.wikipedia.org/wiki/Google_Lighthouse) and has a much larger audience.

As the microservice delegates work, possibly a nautical-themed crew position would suffice. Or a well-known historical or fictional captain or skipper name (e.g.,  Ahab, Barbossa, Gilligan, etc.)

**Comment by keskad** [comment]
Let the Google change the name :grin: I don't know, joking. In my opinion it's not a problem as the Google's project is something totally different in my opinion.
