### ISSUE TITLE
label plugin not working

### ISSUE THREAD

**Issue by zylpsrs** [jenkins-x/lighthouse#1431]
plugins.yaml:

```
plugins:
  example:
  - label
```

when i submit a command `/language en` or `/kind bug`, the webhook report:

```
"msg":"Nonexistent labels: [language/en]"
"level":"info","msg":"Nonexistent labels: [kind/bug]"
```

ref: https://github.com/kubernetes/test-infra/tree/master/label_sync, create a configmap label-config using label.yaml still not working.

**Comment by slimm609** [comment]
Labels plugin and label_sync are not the same thing.  Labels plugin does not create labels and label_sync is not currently part of lighthouse.

**Comment by msvticket** [comment]
I don't think it's a good idea to allow non admins to create labels. You could let the plugin create labels if the user is an admin, but then the admin could do it the normal way in the git provider anyway.
