### ISSUE TITLE
pass a variable with the trigger plugin

### ISSUE THREAD

**Issue by rochana-atapattu** [jenkins-x/lighthouse#1432]
I'm new to Jenkins X and looking to adopt it. 
I wanted promote the build to a specific environment from the PR without promoting to a preview environment (maybe multiple successive environments dev -> qa -> uat). Since i couldn't find any built-in feature to do this (please correct me if I'm wrong), I tried creating a trigger but I was unable to pass an argument with the trigger.
eg : 
_comment `/promote qa` on the PR_

I glanced over the code but I was not able to find a way to pass the variable from trigger to the pipeline. Is there something I'm missing or is this a feature you are considering?

**Comment by msvticket** [comment]
No, that is no feature that exists. I have considered it for other purposes; in my case to specify specific test for an integration test pipeline.

What you could do though is to register multiple triggers that use the same pipeline source but have different triggers and give different parameters to the pipeline using `pipeline_run_params`.

Here you can see how `pipeline_run_params` is used:

https://github.com/jenkins-x/lighthouse/blob/main/pkg/triggerconfig/inrepo/test_data/myorg/myrepo/.lighthouse/jenkins-x/triggers.yaml#L12
