### ISSUE TITLE
/override command not working for admin user on gitea

### ISSUE THREAD

**Issue by zylpsrs** [jenkins-x/lighthouse#1433]
I use gitea as a git repository, and I created an example organization, where user zyl is an administrator in the organization.

When I use `/override`, such as `/override deleted-job`, the feedback user is not an administrator account:

```
@zyl: zyl unauthorized: /override is restricted to repo administrators
```

**Comment by msvticket** [comment]
Currently you are only considered admin in your own organisation. But I have created a PR that when merged should resolve this issue.
