### ISSUE TITLE
what is the issue ? 

### ISSUE THREAD

**Issue by abhilash1786** [jenkins-x/lighthouse#1544]
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "jx-boot" in namespace "jx-git-operator" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "jxgo": current value is "jx-git-operator"'

**Comment by msvticket** [comment]
Not enough details about where this error comes from and in what circumstances.
