### ISSUE TITLE
Using Lighthouse in Tekton only for ChatOps and Status checks

### ISSUE THREAD

**Issue by Stringls** [jenkins-x/lighthouse#1545]
Hi folks! Is that possible to setup Lighthouse to use it only for ChatOps and Status checks as I am running pipielines with Tekton Triggers?
If we can, do I need to setup a separate webhook for lighthouse or I can redirect hook from Tekton Triggers to Lighthouse?

**Comment by msvticket** [comment]
Sure, if you don't configure any pipelines for Lighthouse it won't be able to run any. I don't really understand what good such a set-up would make.

 I'm pretty sure you would need a separate hook.
