### ISSUE TITLE
The default value of GIT_SERVER is "github.com" even if GIT_KIND isn't "github"

### ISSUE THREAD

**Issue by monaka** [jenkins-x/lighthouse#1581]
Referring to the description in README.md,

> GIT_SERVER : the URL of the server if not using the public hosted git providers:

So the default value of `GIT_SERVER` should be `https://gitlab.com` if they set `gitlab` as `GIT_KIND`.
But it looks that the default value of `GIT_SERVER` is always `https://github.com`.

It can be avoided by setting `GIT_SERVER='https://gitlab.com'`  explicitly.

**Comment by msvticket** [comment]
It seems like this is a feature request. Do rewrite the title and description as such.

**Comment by msvticket** [comment]
Issue is confusingly written
