### ISSUE TITLE
Always giving performance matrics when the device selected as mobile

### ISSUE THREAD

**Issue by Chanaka-IG** [jenkins-x/lighthouse#1617]
Always giving performance matrics when the device selected as mobile. As an example when I generate the value for particular web page by selecting device as mobile, for the First Contentful Paint from the front end it gives 3.6 . When I selected desktop as device it gave 1.2. But when I executing the following command it always giving mobile related values. 

const command = `lighthouse ${url} --output ${format} --output-path ${outputPath} --chrome-flags="--headless --no-sandbox" --viewport 1920,1080 --emulated-form-factor=desktop --disable-throttling`;

**Comment by msvticket** [comment]
I'm pretty sure you are confusing this lighthouse with something else
