### ISSUE TITLE
Can't build with Go 1.13

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/lighthouse#251]
Following the README.md instructions to build causes the following error: 

> make build 

generates this error after a fresh a clone:
```
GO111MODULE=on go build -i -ldflags "-X github.com/jenkins-x/lighthouse/pkg/version.Version='-dev+'" -o bin/lighthouse pkg/main/main.go 
go: k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
make: *** [build] Error 1
```

**Comment by patrickwall57** [comment]
did you get past this? Im having the same error

**Comment by nehagup** [comment]
Same here!

**Comment by wtanner** [comment]
I ran into the same issue when I tried to build with Go 1.13 (see "version validation" in the [release notes](https://golang.org/doc/go1.13)). The build succeeded with Go 1.11.

**Comment by nehagup** [comment]
Yes, the build also succeeded with go 1.12.4

**Comment by vishveshv** [comment]
`make build` works go version < 1.13

**Comment by abayer** [comment]
This works for me now with go 1.13.8, fwiw.
