### ISSUE TITLE
Gitlab webook failing with Invalid webhook signature

### ISSUE THREAD

**Issue by MohamedTalhaoui** [jenkins-x/lighthouse#485]
Setting up a fresh jenkins x serverless with gitlab.
I have checked the webhook on the dev repo is correctly configured with the generated hmac token.
However testing the webhook fails with 
```
500 Internal Server Error: Failed to parse webhook: Invalid webhook signature 
```
As a workarounf I removed the hmac token from the webhook configuration and from the lighthouse deployment, then the webhook works

**Comment by abayer** [comment]
Are you still seeing this?

**Comment by sergiu-svinarciuc** [comment]
Yup. There is still no way to configure a webhook in Bitbucket to send the hmac, hence the webhook validation fails.

**Comment by abayer** [comment]
This is specifically about Gitlab - if you're having problems with BitBucket Server, could you open a new issue?

**Comment by sergiu-svinarciuc** [comment]
Uh oh, apologies, missed that in the title.

**Comment by majuansari** [comment]
@sergiu-svinarciuc  You sorted out the issue with bitbucket? I am facing the same issue.

**Comment by valiksb** [comment]
> Setting up a fresh jenkins x serverless with gitlab.
> I have checked the webhook on the dev repo is correctly configured with the generated hmac token.
> However testing the webhook fails with
> 
> ```
> 500 Internal Server Error: Failed to parse webhook: Invalid webhook signature 
> ```
> 
> As a workarounf I removed the hmac token from the webhook configuration and from the lighthouse deployment, then the webhook works

Hi Mohammed could you provide the exact steps to remove the hmac token from both places.

Thanks a lot

**Comment by bryceyang** [comment]
facing the same issue with GitLab Community Edition 13.12.15.
