### ISSUE TITLE
Commits do not trigger PR builds when using Bitbucket Server

### ISSUE THREAD

**Issue by RoVernekar** [jenkins-x/lighthouse#511]
### Scenario 1 - Create PR as non pipeline bot user

Using Bitbucket Server, a PR build does not trigger when creating a PR through the Bitbucket UI as a user other than the pipeline bot user. Instead, the following message is added as a comment:

> Hi *****. Thanks for your PR.
> 
> I'm waiting for a [FOO](https://github.com/orgs/FOO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/FOO/people) to skip this step.
> 
> Once the patch is verified, the new status will be reflected by the `ok-to-test` label.
> 
> I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=).
> 
> <details>
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
> </details>

I'm not sure what the criteria is to determine if the user is part of the project/org here. I'm guessing it's some permission that my pipeline bot user has that my other user doesn't have.

Commenting with `/ok-to-test` does not seem to trigger a build after this happens.

### Scenario 2 - Create PR as pipeline bot user or with `jx create pullrequest`

If the PR is created via the Bitbucket UI as the pipeline bot user or if the PR is created using `jx create pullrequest`, the above welcome comment is not posted and the initial PR build successfully gets kicked off.

Subsequent commits _do not_ trigger new builds. I couldn't figure out any way to get the PR build to trigger again.

**Comment by abayer** [comment]
Are commits to master triggering builds?

**Comment by RoVernekar** [comment]
> Are commits to master triggering builds?

Yes, that works fine.

**Comment by abayer** [comment]
Ok, that's a relief! That means it's just PR pushes that aren't being handled correctly. Thanks!

**Comment by abayer** [comment]
I have reproduced this in a test - but I'm not sure when I'll be able to work on it due to traveling for meetings all next week. We're getting the `push` hook event, but not actually doing anything with it, as best as I can tell from the logs.

**Comment by RoVernekar** [comment]
Okay, no problem. I'll try to manage for now, thanks for taking a look!

**Comment by abayer** [comment]
Sooooo, if the PR is for a branch in the target repo, a `repo:refs_changed` event is sent, but with no information about any related PR, and if the PR is for a branch from a forked repo, _nothing_ gets sent. I'm trying to check with Atlassian to be sure I'm not misunderstanding this and to see if there's anything that can be done about it, but it looks like, at least for the moment, the best option is to close/reopen the PR. Which is absurd, but yeah.

**Comment by joostvdg** [comment]
It seems Atlassian has done something about this as of 7.0: https://jira.atlassian.com/browse/BSERV-10279

The statement:

> Hi everyone,

> Thanks for your feedback and advocacy on this suggestion. In Bitbucket Server and Data Center 7.0 we have introduced a new webhook - 'Source branch updated'. This webhook will send the pull request context when source branch of a pull request is updated e.g. new commits pushed to the source branch. You can check the sample payload on this page.

> Try it out and let us know how it goes.

> Thanks!
> Imran Khan - Product Manager, Bitbucket Server

@abayer should we open a new ticket for supporting this for `7.x`release of Bitbucket server/datacenter?
