### ISSUE TITLE
Azure DevOps git service hooks supported?

### ISSUE THREAD

**Issue by bitsofinfo** [jenkins-x/lighthouse#519]
My code is in Azure DevOps git repositories. Are Azure DevOps git service hooks supported? 

How can I get lighthouse to work w/ azure's service hook calls? (i.e. their webhooks)

**Comment by bitsofinfo** [comment]
#600

**Comment by bitsofinfo** [comment]
#600

**Comment by msvticket** [comment]
Superseded by #600
