### ISSUE TITLE
Lighthouse is hard-coded to master branch for postsubmit

### ISSUE THREAD

**Issue by TonyNoble** [jenkins-x/lighthouse#527]
# jx version info:
```
NAME               VERSION
jx                 2.0.973-dev+e4d57d59e
Kubernetes cluster v1.14.8
kubectl            v1.17.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

# Steps to recreate:
* Import project into jx, specifying branches as 'master|develop'
* Update default-scheduler (or as applicable) to add 'develop' to postsubmit branches
* Push a change to develop branch of imported project

# Expected results:
Pipeline is triggered

# Actual results:
No pipeline is triggered

# Other info
Looking at pkg/plumber/plumber.go , it seems as though the pipeline kind is only ever set to 'postsubmit' for 'master' branch.  Everything else is treated as pre-submit and given that there will be no PR info in the hook payload, presumably this is why nothing else is being triggered either.

Would suggest that all 'push' hooks are treated as postsubmit and all open merge-request hooks treated as presubmit, with further discrimination for actions provided downstream.

**Comment by abayer** [comment]
I _think_ this got fixed along the way - are you still seeing it?
