### ISSUE TITLE
lighthouse: PULL_NUMBER environment variable not set in task

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x/lighthouse#585]
### Summary

Migrating from `prow` - seems that the tasks created by `lighthouse` don't set the `PULL_NUMBER` environment variable.

### Steps to reproduce the behavior

Compare environment set in task created by `prow` with environment set in task created by `lighthouse`.

### Expected behavior

Environment is set.

### Actual behavior

Pipeline steps that depend on `PULL_NUMBER` fail.

**Comment by abayer** [comment]
Hrrrm - I could have sworn I saw it in my testbed, lemme verify.

**Comment by abayer** [comment]
It definitely shows up on the metapipeline, verifying now w.r.t. the generated pipeline. What version is the image in `kubectl get deployment jenkins-x-lighthouse -o yaml`?

**Comment by abayer** [comment]
Confirmed that `jx-requirements.yml` was pointing to a specific, older ref in `jenkins-x-versions`, so that needed to be updated.
