### ISSUE TITLE
Define and manage the configuration required to setup a webhook

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/lighthouse#6]
The lighthouse will need some configuration management in order to be able to listen to events coming from a webhook. This configuration is GIt provider specific but we should try to design it in a generic way.

**Comment by jstrachan** [comment]
the current spike uses the existing `SourceRepository` resources to know if a repository is being handled by lighthouse - though we don't yet load the configuration from the assocated `Schedule` (either linked on the SR or via a `SourceRepositoryGroup` or via the default `Schedule` on the dev `Environment`

**Comment by jstrachan** [comment]
gonna close this - the remaining stuff is here: https://github.com/jenkins-x/lighthouse/issues/10

**Comment by wbrefvem** [comment]
I think we should discuss how config should be handled -- i.e., through flags or a config file(s) or some combination of both.

**Comment by jstrachan** [comment]
see #10
