### ISSUE TITLE
no auto-assignment of reviewers on github

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/lighthouse#770]
previously on CJXD 9, when creating a new PR on github, prow used to automatically assign reviewers based on the content of the OWNERS file.

now with CJXD 10 on the same cluster, lighthouse doesn't automatically assign reviewers anymore. but using the `/assign` cmd in a PR comment still works.

Not sure if it's on purpose or a missing feature.

thanks

**Comment by abayer** [comment]
Yeah, I kinda hated the logic behind how it did this and had some bugs with it on non-GitHub providers, so I disabled it. I'll try to come back to it.
