### ISSUE TITLE
Lighthouse webhook service is too chatty about itself

### ISSUE THREAD

**Issue by achedeuzot** [jenkins-x/lighthouse#781]
I've just upgraded to the lastest jx without issues 🎉 . I noticed the switch from prow to lighthouse.

I did a quick `curl` on the webhook URL to check if everything is working OK and I noticed the following response:

```bash
$ curl http://hook.example.com/
Hello from Jenkins X Lighthouse version: '0.0.611'
For more information see: https://github.com/jenkins-x/lighthouse
```

I find this response too verbose given the fact that we have a private cluster and the webhook is the only public endpoint we expose. This is providing too much information publicly. Is it possible to reduce the verbosity of the response of the webhook service ? Thanks !

**Comment by abayer** [comment]
I honestly never thought about this. Looks like Prow just returns nothing, so I guess we should do the same.
