### ISSUE TITLE
Invalid link to the OWNERS file in the APPROVALNOTIFIER comments

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/lighthouse#782]
the comments generated by lighthouse for the APPROVALNOTIFIER contains links to the OWNERS files, but these links are invalid: https://github.com/org/repo/pull/org/repo/blob/master/OWNERS instead of https://github.com/org/repo/blob/master/OWNERS

with v0.0.624 using github.com

**Comment by abayer** [comment]
This is surprisingly weird to figure out the cause - I think it's gotta be some dumb pointer logic somewhere. I need to throw a bunch of tests at this.
