### ISSUE TITLE
Lighthouse outside JenkinsX

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/lighthouse#794]
Hi,

Could anyone please let me know whether I can use  lighthouse outside of Jenkins-X platform?
I'm using tekton pipeline and want to know whether I can use lighthouse with tekton (without using jenkinsx platform).

Thanks !

**Comment by jstrachan** [comment]
the jx controller just released which decouples the Jenkins X Pipeline part - so we should be able to create a pure tekton based controller now that turns `LighthouseJob` resources into tekton pipelines

**Comment by eddycharly** [comment]
It looks like the was resolved, feel free to reopen if needed.

/close
