### ISSUE TITLE
restarting pipeline with `/retest` fails to trigger the pipline

### ISSUE THREAD

**Issue by vivekthangathurai** [jenkins-x/lighthouse#796]
I am running Jenkins X in GKE and lighthouse for webhooks
Jx version: 2.1.35

Please help me debug the issue.

**Comment by abayer** [comment]
Can you give more details? `/retest` only fires when the previous run had failed. Assuming that's the case for you, could you attach your `lighthouse-webhook` pod logs? Feel free to scrub them of any identifying information, but let me know which repo and PR you're trying to retest so I can find the info in the logs.

**Comment by vivekthangathurai** [comment]
I took the logs from when I commented `/retest`
The project is AppDirect/jenkinx-springboot-gradle.git
```
{"Branch":"master","Clone":"https://github.com/AppDirect/jenkinx-springboot-gradle.git","ID":"268033684","Link":"https://github.com/AppDirect/jenkinx-springboot-gradle","Name":"jenkinx-springboot-gradle","Namespace":"AppDirect","Webhook":"issue_comment","level":"info","msg":"invoking Issue Comment handler","time":"2020-06-12T13:07:00Z"}
{"Branch":"master","Clone":"https://github.com/AppDirect/jenkinx-springboot-gradle.git","ID":"268033684","Link":"https://github.com/AppDirect/jenkinx-springboot-gradle","Name":"jenkinx-springboot-gradle","Namespace":"AppDirect","Webhook":"issue_comment","author":"vivekthangathurai","level":"info","msg":"Issue comment created.","org":"AppDirect","pr":5,"repo":"jenkinx-springboot-gradle","time":"2020-06-12T13:07:00Z","url":"https://github.com/AppDirect/jenkinx-springboot-gradle/pull/5#issuecomment-643260424"}
{"level":"info","msg":"found plugins approve, assign, blunderbuss, help, hold, lgtm, lifecycle, override, size, trigger, wip, heart, cat, dog, pony\n","time":"2020-06-12T13:07:00Z"}
{"level":"info","msg":"found plugins approve, assign, blunderbuss, help, hold, lgtm, lifecycle, override, size, trigger, wip, heart, cat, dog, pony\n","time":"2020-06-12T13:07:00Z"}
```

**Comment by abayer** [comment]
Is there anything below those lines?

**Comment by vivekthangathurai** [comment]
Nothing below those lines.

**Comment by abayer** [comment]
And your pipeline is failed? What happens if you try `/test this`?

**Comment by vivekthangathurai** [comment]
yes failed. I get the same log
```
{"Branch":"master","Clone":"https://github.com/AppDirect/jenkinx-springboot-gradle.git","ID":"268033684","Link":"https://github.com/AppDirect/jenkinx-springboot-gradle","Name":"jenkinx-springboot-gradle","Namespace":"AppDirect","Webhook":"issue_comment","level":"info","msg":"invoking Issue Comment handler","time":"2020-06-12T16:10:12Z"}
{"Branch":"master","Clone":"https://github.com/AppDirect/jenkinx-springboot-gradle.git","ID":"268033684","Link":"https://github.com/AppDirect/jenkinx-springboot-gradle","Name":"jenkinx-springboot-gradle","Namespace":"AppDirect","Webhook":"issue_comment","author":"vivekthangathurai","level":"info","msg":"Issue comment created.","org":"AppDirect","pr":5,"repo":"jenkinx-springboot-gradle","time":"2020-06-12T16:10:12Z","url":"https://github.com/AppDirect/jenkinx-springboot-gradle/pull/5#issuecomment-643355870"}
{"level":"info","msg":"found plugins approve, assign, blunderbuss, help, hold, lgtm, lifecycle, override, size, trigger, wip, heart, cat, dog, pony\n","time":"2020-06-12T16:10:12Z"}
{"level":"info","msg":"found plugins approve, assign, blunderbuss, help, hold, lgtm, lifecycle, override, size, trigger, wip, heart, cat, dog, pony\n","time":"2020-06-12T16:10:12Z"}
```

**Comment by abayer** [comment]
Right, but why is the pr-build failing? What do you see in `jx get build log` for it?

**Comment by abayer** [comment]
Oops, wrong thread. Ignore me. =) Can you verify that https://github.com/AppDirect/jenkinx-springboot-gradle/pull/5#issuecomment-643355870 is the `/test this` comment?

**Comment by vivekthangathurai** [comment]
I made the PR build fail. and wanted to retrigger it via chat ops. Yes the comment link is for `/test this`.  have I understood the functionality wrong?

**Comment by abayer** [comment]
No, you've got it right, I just can't reproduce this, and we explicitly test this exact functionality in our BDD tests, so I'm confused. Can you check what image version of `lighthouse-webhooks` is in use in your pods?

**Comment by paul-g1** [comment]
Hi, I too am seeing this issue. None of the /test commands seem to work, others (like woof) do.
I have very similar output in my webhooks log ("found plugins approve......pony", then nothing).

I'm using jx 2.1.62, lighthouse-webhooks 0.0.706, and tested with a spring quickstart app with no changes except a unit test that fails on purpose.

Is there anything you'd like me to try?
