### ISSUE TITLE
add global OWNERS_ALIASES

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/lighthouse#798]
It would be great to have global aliases for the approval plugin, that are defined at the lighthouse level, and applied to all repositories "managed" by lighthouse.

our use case is that we have lots of repositories and well-identified teams working on a large set of repos. If possible we'd like to avoid duplicating OWNERS_ALIASES files.

thanks

**Comment by abayer** [comment]
Folding this into #436 - this was already my next planned feature work. =)

**Comment by vbehar** [comment]
oh nice, sorry I missed this existing issue.
