### ISSUE TITLE
Tekton pipeline status reporting for GitHub/GitHub enterprise

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/lighthouse#83]
After evaluating the current [pullRequest](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource) resource in Tekton, it seems that is not currently working and requires some additional development. 

This work should cover:
- defining a viable solution for status reporting based on the current Tekton architecture and `pullRequest` resource  
- Implement the required changes
- Validate and add E2E tests in Tekton for it. 

The elated issues in Tekton: https://github.com/tektoncd/pipeline/issues/49 and https://github.com/tektoncd/pipeline/issues/1149 and

**Comment by jstrachan** [comment]
BTW this is now fixed - we have a `--git-reporting` flag on build controller is enabled in `jx boot` for lighthouse now https://jenkins-x.io/commands/jx_controller_build/ which reports git status for github/GHE/BBS/gitlab
