### ISSUE TITLE
get version stream BDD tests working for Bitbucket Server

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/lighthouse#86]
once we get the version stream BDD tests passing for Bitbucket Server it will give us greater confidence as we refactor/improve the codebase.

Current BDD test is here: https://github.com/jenkins-x/jenkins-x-versions/tree/master/jx/bdd/boot-lh-bs

**Comment by ccojocar** [comment]
Also this is not in scope for phase 1.

**Comment by jstrachan** [comment]
sorted see https://github.com/jenkins-x/jenkins-x-versions/tree/master/jx/bdd/boot-lh-bs - we've not enabled it by default yet but seems to work every time we trigger
