### ISSUE TITLE
create BDD test for gitlab

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/lighthouse#88]
we don't yet have a BDD test to verify the gitlab support

**Comment by ccojocar** [comment]
@jstrachan this is not in scope for phase 1.

**Comment by jstrachan** [comment]
agreed - just wanted to leave it on the backlog for now

**Comment by jstrachan** [comment]
done - see https://github.com/jenkins-x/jenkins-x-versions/tree/master/jx/bdd/boot-lh-gl
