### ISSUE TITLE
Support Kubernetes job for pipeline execution

### ISSUE THREAD

**Issue by abayer** [jenkins-x/lighthouse#884]
Let's keep adding engines! So that means Kubernetes job execution, like Prow.

**Comment by abayer** [comment]
So I'm taking a look at this, and it's not actually jobs, it's pods, and I'm honestly wondering if we should bother supporting this. The Prow implementation requires a bunch of magic using GCS for storing information to use for cloning/checking status of the clone and other stuff. Need to think on this more.

@eddycharly - do you have any thoughts on this?

**Comment by eddycharly** [comment]
That should be pretty easy to support, just throw away all the GCS part... we don't care.

At least for a first implementation, inject an init container that clones the source and mounts it in the pod should be enough i guess.
IIRC, the job spec is serialized in json and sent to the pod as an env variable.

**Comment by abayer** [comment]
Yeah, there's also sidecar logic for capturing and uploading logs...I guess I'm wondering how useful the whole thing would be without the magic provided by GCS integration.

**Comment by eddycharly** [comment]
In the last months s3 support was added too, it was a nightmare, the guy who worked on this had PRs opened for weeks and it was really challenging.

IMO this is too complex and not open enough, we have other solutions for collecting logs that work well and this sidecar thing doesn't really make sense to me.

For the cloning part, having the init container take care of this is probably a good thing.

**Comment by abayer** [comment]
Yeah, lemme think up and write up what we'd actually have the pod support do...
