### ISSUE TITLE
Have a way to NOT test a PR right away

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/lighthouse#886]
Hi,

we have a use-case where we'd like to NOT execute the tests on a PR at the PR creation: our use-case is the creation of dozens of PRs when we bump the version of our jx buildpacks, or our base Helm chart for example. In that case, we want to create a PR on all the repos using the buildpack or base Helm chart, but triggering the tests on all these repos (there can be dozens or hundreds of them) might overwhelm the jx cluster.

In that case, we'd like to create the PRs but not run the tests automatically, and let the repos maintainers choose when they want to run the tests, using the chatops commands. Note that all our repos are private, and we can't use a bot that is not in our org otherwise it won't have access to our repos to create the PRs.

Ideally, we'd like to be able to add a label when creating the PRs, such as `needs-ok-to-test`, and the presence of such a label will disable the automatic trigger of the lighthouse jobs. Then, commenting with `/ok-to-test` will remove the label, and trigger the tests.

What do you think? Is there a better way to solve our issue that matches our use-case?

Thanks!

**Comment by abayer** [comment]
So I think if you set `alwaysRun: false` but leave it in the required contexts list, the context won't run automatically but still will be required. Then `/test foo` will run it on demand. But a broader approach could be interesting, yeah.

**Comment by abayer** [comment]
Ah, and yeah, what you're looking for is creating a PR and saying "don't run the tests for this PR right away" - we can definitely do something like that, probably like that label approach you mentioned. Seems reasonable/easy enough.

**Comment by abayer** [comment]
And fwiw, `needs-ok-to-test` won't work - that gets automatically removed from any PR from a trusted user on reopen, and is ignored on open anyway. We'd need a new label for this, but that should be pretty trivial. I'm thinking `waiting-for-ok-to-test` - we then special-case the open/reopen/changes to the PR cases to skip building if `waiting-for-ok-to-test` present, and have `/ok-to-test` also remove `waiting-for-ok-to-test` as well as `needs-ok-to-test`.

**Comment by vbehar** [comment]
yes exactly, most of the time we want the tests to run automatically (when devs create PRs), but for specific use-case like this one, we'd like to have the ability to run the tests later, manually.

I tried the`needs-ok-to-test` label, but it didn't work, as you said the code validates the PR author first, and in our case the bot is part of the org, so it's always able to activate the automatic trigger of the tests.

adding a `waiting-for-ok-to-test` at PR creation is totally fine for us, that would be perfect, that way we could control which PRs would not have their tests run automatically

**Comment by abayer** [comment]
Okiedokie, I'll try to get that done in the next few days while I'm working on my Lighthouse presentation for the CDF Interop SIG on Thursday and trying to find something else to do. =)

**Comment by abayer** [comment]
Argh, just realized this won't work - there is no way to specify labels when creating a PR on GitHub, you can only add them after the fact, so we'll end up running the builds on PR creation even if we then add the label. Hrm.

**Comment by vbehar** [comment]
oh you're right... we'll need another solution

**Comment by abayer** [comment]
Best I can think of off the top of my head is to look for something in the PR body text and add the label if we see it (and don't build initially, of course), but only doing so on open...but let's think on this for a bit before I dive back in.

**Comment by vbehar** [comment]
agreed, this sounds too much like a hack ;-)

**Comment by abayer** [comment]
It would all be so simple if GitHub just allowed you to specify labels at PR creation time! They do for issues, but not PRs. Grr!

**Comment by vbehar** [comment]
I have an idea:
- in the config, a list of users for which we'll never automatically run the tests. some kind of a "blacklist", that would be check before checking if the user is part of the org. This would allow a user to be in the org (so that it can see the private repos), but not allowed to automatically have its tests executed.
- and if for some PRs we want to allow automatic triggering of the tests for this user/bot, we could either comment with a `/ok-to-test` or just add the `ok-to-test` label (or remove the `needs-ok-to-test` label that would be added by lighthouse automatically)

what do you think?

**Comment by eddycharly** [comment]
For GitHub this can be done with the draft PR status. Not sur if that applies to other providers though...
