### ISSUE TITLE
Enable test coverage and identify which areas needs more testing

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/lighthouse#91]
Enable test coverage and identify which area needs more unit testing after that we should create an issues with more details which needs more testing. 

Enable codeconv into the pipeline file and add a secret for its token that the test reports can be uploaded.

**Comment by wbrefvem** [comment]
I've begun breaking this out into smaller chunks, the first of which is #352.

**Comment by wbrefvem** [comment]
At the moment, it seems that the packages ported over from prow have good unit testing, but the packages we've added do not. There's quite a bit to be done to add unit tests that will hopefully help prevent regressions as development ramps up.
