### ISSUE TITLE
Code gen is broken

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#926]
The commit https://github.com/jenkins-x/lighthouse/commit/8353df545b1987eb04fd6e24130c3cd8ff30ee5f#diff-f26c1f2e029e419697a22d9c956a92aa moved some files in `pkg/apis/lighthouse/v1alpha1`.

Unfortunately those types are breaking code gen.

**Comment by abayer** [comment]
Argh, yeah, I’ll take a look tomorrow.

**Comment by abayer** [comment]
I'm seriously tempted to just revert out the `repoconfig` stuff entirely and wait til we actually implement the whole feature.

**Comment by eddycharly** [comment]
Can't you just move it ouside of `v1alpha1` ?

**Comment by abayer** [comment]
Yeah, but I don't like that we've got duplicates of the same structs in `repoconfig` and `config` just to change the json keys. It's annoying. And since it's not actually _used_ for anything, I just wonder if there's really a point in having it in here until we actually use it.

**Comment by abayer** [comment]
And I really need to add a better codegen thing in here in the first place, since what I've got is a hack of a hack.

**Comment by eddycharly** [comment]
It would be nice to verify code gen in ci too.

**Comment by abayer** [comment]
https://github.com/jenkins-x/lighthouse/pull/939 just simplifies things for the moment and adds the check.
