### ISSUE TITLE
Migrate tekton controller to controller-runtime

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#933]
There’s a lot of boilerplate code in the tekton controller.

How about migrating the controller to controller-runtime ? This would simplify the implementation enormously and would be a lot easier to maintain.

**Comment by abayer** [comment]
That would be fine by me.

**Comment by eddycharly** [comment]
Ok, I started something https://github.com/jenkins-x/lighthouse/pull/938.

Still WIP but so far it eliminated most of the boilerplate code.
