### ISSUE TITLE
Is dryRun used ?

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#941]
https://github.com/jenkins-x/lighthouse/blob/c4078df39875c899c9078575a8c9ac9fe08603f9/cmd/tektoncontroller/main.go#L21

Is the `dryRun` flag used at all ?
If not, shall we remove it ?

**Comment by abayer** [comment]
Looks like it's not - I must have stopped using it before actually finishing things. Whoops! I'm about to open a PR for moving `foghorn` to controller-runtime - I'll remove this in that PR.
