### ISSUE TITLE
docker container built from 'Dockerfile.webhooks' failed with log message "no such file or directory"

### ISSUE THREAD

**Issue by docularxu** [jenkins-x/lighthouse#945]
Does anybody run into such problem when runing docker container built from 'Dockerfile.webhooks'? 
 -- "standard_init_linux.go:178: exec user process caused "no such file or directory" "

I met this issue on both x86-64 machines and arm64 machines. Interestingly, if I changed the first line of Dockerfile.webhooks from 'alpine:3.10' to 'FROM ubuntu:18.04', this problem disappeared. 

Here is what I did: 
Step 1.
$ make build 
It can produce './bin/lighthouse' as expected. Then, I run:
Step 2.
$ docker build -f Dockerfile.webhooks -t  lighthouse:webhooks .
$ docker run -d lighthouse:webhooks
$ docker logs <containerID>
 "standard_init_linux.go:211: exec user process caused "no such file or directory".

Thank you.

**Comment by docularxu** [comment]
By the way, code base we are using is this: v0.0.738
$ git clone -b v0.0.738  https://github.com/jenkins-x/lighthouse.git

**Comment by abayer** [comment]
Hrm, weird that we don’t see this running the container in Kubernetes. I’ll take a look.
