### ISSUE TITLE
Any reason why keeper.imagePullPolicy is not made on the same pattern as others ?

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#982]
https://github.com/jenkins-x/lighthouse/blob/53f2eae69b75b62d1b6e2a4910e8a3dd8072d63f/charts/lighthouse/values.yaml#L163

For example, foghorn (and all other elements in the chart) uses `keeper.image.pullPolicy`.

**Comment by abayer** [comment]
Accidental. =)

**Comment by eddycharly** [comment]
Ok, i'll make it consistent then.
