### ISSUE TITLE
Enable using a file/folder/configmap for jobs

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#998]
It looks like the current implementation does not allow for loading jobs from a separate file or folder (except in `config.Load`).

It would be nice to support this as well. It copes well with the way `OWNERS` works.

**Comment by abayer** [comment]
Yeah, Prow supports that approach, seems like a reasonable addition.

**Comment by eddycharly** [comment]
I guess it’s intentional to not mount config maps in the pods ?

**Comment by abayer** [comment]
Yeah, at some point we switched to watching the configmaps rather than mounting them. I honestly don't know why that was done originally, but I've just done it everywhere now. =)

**Comment by eddycharly** [comment]
Ok, I guess it’s to avoid pods getting stuck when the config maps don’t exist.
I will take the same approach here.

**Comment by abayer** [comment]
Oh riiiiiight that's why I switched to that on Keeper. =)
